name: ci-cd

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: read

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Run unit tests
        run: go test ./...

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web:${{ steps.vars.outputs.TAG }}

      - name: Update k8s manifest with new image tag
        run: |
          sed -i "s#image: .*#image: ${{ secrets.DOCKERHUB_USERNAME }}/go-web:${{ steps.vars.outputs.TAG }}#g" k8s/deployment.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "chore: bump image to ${{ steps.vars.outputs.TAG }}"
          git push
